/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ApiGenerateVideoRouteImport } from './routes/api/generate-video'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppCreateRouteImport } from './routes/app.create'
import { Route as AppPricingRouteImport } from './routes/app.pricing'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as ApiVideoContentJobIdRouteImport } from './routes/api/video-content.$jobId'
import { Route as ApiVideoStatusJobIdRouteImport } from './routes/api/video-status.$jobId'
import { Route as ApiVideoTokenJobIdRouteImport } from './routes/api/video-token.$jobId'
import { Route as AppProjectsIndexRouteImport } from './routes/app.projects.index'
import { Route as AppProjectsProjectIdRouteImport } from './routes/app.projects.$projectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateVideoRoute = ApiGenerateVideoRouteImport.update({
  id: '/api/generate-video',
  path: '/api/generate-video',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCreateRoute = AppCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppRoute,
} as any)
const AppPricingRoute = AppPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const ApiVideoContentJobIdRoute = ApiVideoContentJobIdRouteImport.update({
  id: '/api/video-content/$jobId',
  path: '/api/video-content/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVideoStatusJobIdRoute = ApiVideoStatusJobIdRouteImport.update({
  id: '/api/video-status/$jobId',
  path: '/api/video-status/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVideoTokenJobIdRoute = ApiVideoTokenJobIdRouteImport.update({
  id: '/api/video-token/$jobId',
  path: '/api/video-token/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/api/generate-video': typeof ApiGenerateVideoRoute
  '/app/create': typeof AppCreateRoute
  '/app/pricing': typeof AppPricingRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/api/video-content/$jobId': typeof ApiVideoContentJobIdRoute
  '/api/video-status/$jobId': typeof ApiVideoStatusJobIdRoute
  '/api/video-token/$jobId': typeof ApiVideoTokenJobIdRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/app/projects/': typeof AppProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/api/generate-video': typeof ApiGenerateVideoRoute
  '/app/create': typeof AppCreateRoute
  '/app/pricing': typeof AppPricingRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
  '/api/video-content/$jobId': typeof ApiVideoContentJobIdRoute
  '/api/video-status/$jobId': typeof ApiVideoStatusJobIdRoute
  '/api/video-token/$jobId': typeof ApiVideoTokenJobIdRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/app/projects': typeof AppProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/api/generate-video': typeof ApiGenerateVideoRoute
  '/app/create': typeof AppCreateRoute
  '/app/pricing': typeof AppPricingRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/api/video-content/$jobId': typeof ApiVideoContentJobIdRoute
  '/api/video-status/$jobId': typeof ApiVideoStatusJobIdRoute
  '/api/video-token/$jobId': typeof ApiVideoTokenJobIdRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/app/projects/': typeof AppProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/api/generate-video'
    | '/app/create'
    | '/app/pricing'
    | '/app/settings'
    | '/app/'
    | '/api/video-content/$jobId'
    | '/api/video-status/$jobId'
    | '/api/video-token/$jobId'
    | '/app/projects/$projectId'
    | '/app/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/api/generate-video'
    | '/app/create'
    | '/app/pricing'
    | '/app/settings'
    | '/app'
    | '/api/video-content/$jobId'
    | '/api/video-status/$jobId'
    | '/api/video-token/$jobId'
    | '/app/projects/$projectId'
    | '/app/projects'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/api/generate-video'
    | '/app/create'
    | '/app/pricing'
    | '/app/settings'
    | '/app/'
    | '/api/video-content/$jobId'
    | '/api/video-status/$jobId'
    | '/api/video-token/$jobId'
    | '/app/projects/$projectId'
    | '/app/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  ApiGenerateVideoRoute: typeof ApiGenerateVideoRoute
  ApiVideoContentJobIdRoute: typeof ApiVideoContentJobIdRoute
  ApiVideoStatusJobIdRoute: typeof ApiVideoStatusJobIdRoute
  ApiVideoTokenJobIdRoute: typeof ApiVideoTokenJobIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-video': {
      id: '/api/generate-video'
      path: '/api/generate-video'
      fullPath: '/api/generate-video'
      preLoaderRoute: typeof ApiGenerateVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/create': {
      id: '/app/create'
      path: '/create'
      fullPath: '/app/create'
      preLoaderRoute: typeof AppCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pricing': {
      id: '/app/pricing'
      path: '/pricing'
      fullPath: '/app/pricing'
      preLoaderRoute: typeof AppPricingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/video-content/$jobId': {
      id: '/api/video-content/$jobId'
      path: '/api/video-content/$jobId'
      fullPath: '/api/video-content/$jobId'
      preLoaderRoute: typeof ApiVideoContentJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/video-status/$jobId': {
      id: '/api/video-status/$jobId'
      path: '/api/video-status/$jobId'
      fullPath: '/api/video-status/$jobId'
      preLoaderRoute: typeof ApiVideoStatusJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/video-token/$jobId': {
      id: '/api/video-token/$jobId'
      path: '/api/video-token/$jobId'
      fullPath: '/api/video-token/$jobId'
      preLoaderRoute: typeof ApiVideoTokenJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/projects/': {
      id: '/app/projects/'
      path: '/projects'
      fullPath: '/app/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects/$projectId': {
      id: '/app/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/app/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCreateRoute: typeof AppCreateRoute
  AppPricingRoute: typeof AppPricingRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCreateRoute: AppCreateRoute,
  AppPricingRoute: AppPricingRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppProjectsProjectIdRoute: AppProjectsProjectIdRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  ApiGenerateVideoRoute: ApiGenerateVideoRoute,
  ApiVideoContentJobIdRoute: ApiVideoContentJobIdRoute,
  ApiVideoStatusJobIdRoute: ApiVideoStatusJobIdRoute,
  ApiVideoTokenJobIdRoute: ApiVideoTokenJobIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
